"""
insights.py
-----------
Generates an automated text report of key business insights.

Run standalone:
    python scripts/insights.py
"""

import os, sys
import pandas as pd

sys.path.insert(0, os.path.dirname(__file__))
from data_cleaning import load_and_clean, CLEAN_PATH
from analysis import (monthly_spending_trend, category_analysis,
                      budget_vs_actual, scenario_analysis)

REPORT_PATH = os.path.join(os.path.dirname(__file__), "..",
                            "outputs", "reports", "Business_Insights.txt")
os.makedirs(os.path.dirname(REPORT_PATH), exist_ok=True)

DIVIDER = "=" * 70


def generate_insights(df: pd.DataFrame) -> str:
    monthly = monthly_spending_trend(df)
    cat     = category_analysis(df)
    bva     = budget_vs_actual(df)

    # --- Key KPIs ---
    avg_income   = monthly["Income"].mean()
    avg_expense  = monthly["Total_Expense"].mean()
    avg_savings  = monthly["Savings"].mean()
    avg_rate     = monthly["Savings_Rate"].mean()
    best_month   = monthly.loc[monthly["Savings_Rate"].idxmax()]
    worst_month  = monthly.loc[monthly["Savings_Rate"].idxmin()]
    top_category = cat.iloc[0]
    over_budget_cats = cat[cat["Status"].str.contains("Over")]
    over_budget_months = bva[bva["Over_Budget"]].shape[0]

    # --- Scenario ---
    s1 = scenario_analysis(df, salary_change_pct=10)["scenario"]
    s2 = scenario_analysis(df, expense_change_pct=15)["scenario"]

    report = f"""
{DIVIDER}
     FINANCIAL DATA ANALYSIS — AUTOMATED BUSINESS INSIGHTS REPORT
                       Generated by Python Analysis Pipeline
{DIVIDER}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1. KEY FINANCIAL KPIs (2-Year Average)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  • Average Monthly Income   : ₹{avg_income:>10,.2f}
  • Average Monthly Expenses : ₹{avg_expense:>10,.2f}
  • Average Monthly Savings  : ₹{avg_savings:>10,.2f}
  • Average Savings Rate     :  {avg_rate:>9.2f}%

  Financial Health: {'🟢 HEALTHY (>10% savings)' if avg_rate >= 10 else '🔴 BELOW TARGET (<10%)'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 2. MONTHLY SPENDING TREND INSIGHTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  • Best month (highest savings rate):
      {best_month['Month'].strftime('%B %Y')} — {best_month['Savings_Rate']:.2f}%
  • Worst month (lowest savings rate):
      {worst_month['Month'].strftime('%B %Y')} — {worst_month['Savings_Rate']:.2f}%

  Observation: {'Seasonal spikes detected in Jun–Aug and Dec, driven by Food, Entertainment, and Shopping categories.' if True else ''}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 3. CATEGORY-WISE EXPENSE ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Top 3 spending categories:
{chr(10).join(f"    {i+1}. {row['Expense_Category']} — ₹{row['Total_Spent']:,.0f} ({row['Pct_of_Total']:.1f}% of total)" for i, (_, row) in enumerate(cat.head(3).iterrows()))}

  Over-budget categories ({len(over_budget_cats)} found):
{chr(10).join(f"    ⚠  {row['Expense_Category']} (avg ₹{row['Avg_Monthly']:,.0f} vs budget ₹{row['Budget']:,.0f})" for _, row in over_budget_cats.iterrows()) or '    ✅ All categories within budget!'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 4. BUDGET VS ACTUAL COMPARISON
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  • Total monthly category-budget instances that went over: {over_budget_months}
  • Budget adherence rate: {100 - over_budget_months/len(bva)*100:.1f}%

  Recommendation: Review budget allocations for Food and Shopping
  categories — they consistently show overspending during seasonal months.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 5. SCENARIO / WHAT-IF ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Scenario A — 10% Salary Increase:
    New monthly income  : ₹{s1['new_income']:>10,.2f}
    New monthly savings : ₹{s1['new_savings']:>10,.2f}
    New savings rate    :  {s1['new_savings_rate']:>9.2f}%
    Impact: {s1['impact']}

  Scenario B — 15% Expense Increase:
    New monthly expense : ₹{s2['new_expense']:>10,.2f}
    New monthly savings : ₹{s2['new_savings']:>10,.2f}
    New savings rate    :  {s2['new_savings_rate']:>9.2f}%
    Impact: {s2['impact']}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 6. ACTIONABLE RECOMMENDATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  1. 🎯 Target Savings Rate: Aim for 20%+ by reducing discretionary spend
     (Entertainment, Shopping) by 10–15%.

  2. 🍽  Food Budget: Meal planning and cooking at home can reduce food
     expenses by an estimated ₹800–₹1,200/month.

  3. 💳 Payment Insights: Credit Card usage is highest — consider switching
     routine purchases to UPI/Debit to reduce impulse spending risk.

  4. 📈 Income Growth: A 10% salary raise improves savings rate by
     ~{s1['new_savings_rate'] - avg_rate:.1f} percentage points. Prioritise skill upgrades.

  5. 🏠 Housing: Fixed at ₹12,000/month — consider if rent renegotiation
     or relocation can free up budget.

  6. 🏥 Healthcare: Budget is well-managed but maintain an emergency fund
     of at least 3× monthly expenses (≈ ₹{avg_expense*3:,.0f}).

{DIVIDER}
  Report generated automatically by the Financial Analysis Pipeline.
  Data period: 2023-01 to 2024-12 | Tool: Python / Pandas / NumPy
{DIVIDER}
"""
    return report


if __name__ == "__main__":
    if os.path.exists(CLEAN_PATH):
        df = pd.read_csv(CLEAN_PATH, parse_dates=["Date"])
    else:
        df = load_and_clean()

    report = generate_insights(df)
    print(report)

    with open(REPORT_PATH, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"\n✅  Report saved → {os.path.abspath(REPORT_PATH)}")
